name: Client-side (prod)

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "**/package-lock.json"
    
    - name: Install dependencies
      run: npm install

    - name: Build client-side
      run: npm run build --if-present
    # - run: npm test

    - name: Upload artifact (static content)
      uses: actions/upload-artifact@master
      with:
        name: client-static
        path: client/dist/

  deploy:
    needs: build
    if: success()

    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://universityweb.site

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_DEPLOY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      working-directory: .

    - uses: actions/checkout@master

    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@releases/v1
      id: deployment
      with:
        token: "${{ github.token }}"
        target_url: https://universityweb
        environment: prod

    - name: Download static content
      uses: actions/download-artifact@master
      with:
        name: client-static
        path: dist/
    - name: Deploy static content to local server (rsync)
      run: rsync -av dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/universityweb/

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://universityweb.site
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://universityweb.site
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
